// Generates firmware/device_key.h (P-256 static ECDH keypair) and
// firmware/device_fingerprint.txt (SHA-256 of the 65-byte public key).
// Idempotent: if device_key.h already exists it is never regenerated.
// The fingerprint file is (re)generated when missing by parsing device_key.h.
// Run by CMake at configure time; can also be run manually:
//   node gen_device_key.mjs
import { generateKeyPairSync, createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const dir = dirname(fileURLToPath(import.meta.url));
const keyPath = join(dir, 'device_key.h');
const fpPath = join(dir, 'device_fingerprint.txt');

const fmtArray = (buf, perLine = 12) => {
  const items = [...buf].map((b) => '0x' + b.toString(16).padStart(2, '0'));
  const lines = [];
  for (let i = 0; i < items.length; i += perLine)
    lines.push('  ' + items.slice(i, i + perLine).join(', '));
  return lines.join(',\n');
};

function writeFingerprint(pub) {
  const fp = createHash('sha256').update(pub).digest('hex');
  const short = fp
    .slice(0, 16)
    .replace(/(.{4})/g, '$1 ')
    .trim();
  writeFileSync(
    fpPath,
    `SHA-256(device public key, 65 bytes 0x04||X||Y):\n${fp}\n\nshort:\n${short}\n`,
  );
  console.log(`gen_device_key: fingerprint short = ${short}`);
}

if (!existsSync(keyPath)) {
  const { privateKey } = generateKeyPairSync('ec', { namedCurve: 'P-256' });
  const jwk = privateKey.export({ format: 'jwk' });
  const d = Buffer.from(jwk.d, 'base64url');
  const x = Buffer.from(jwk.x, 'base64url');
  const y = Buffer.from(jwk.y, 'base64url');
  if (d.length !== 32 || x.length !== 32 || y.length !== 32)
    throw new Error('unexpected JWK key size');
  const pub = Buffer.concat([Buffer.from([0x04]), x, y]);
  writeFileSync(
    keyPath,
    `#pragma once
/* Auto-generated by gen_device_key.mjs. Static device ECDH key (secp256r1).
 * Do NOT commit (gitignored). Delete only to rotate the device identity. */
#include <stdint.h>

static const uint8_t PICO2KVM_DEV_PRIV[32] = {
${fmtArray(d)}
};

/* Uncompressed point: 0x04 || X || Y */
static const uint8_t PICO2KVM_DEV_PUB[65] = {
${fmtArray(pub)}
};
`,
  );
  writeFingerprint(pub);
  console.log('gen_device_key: generated device_key.h');
} else {
  if (!existsSync(fpPath)) {
    // Recover the public key bytes from the existing header.
    const src = readFileSync(keyPath, 'utf8');
    const m = src.match(/PICO2KVM_DEV_PUB\[65\][^=]*=\s*\{([^}]*)\}/s);
    if (!m) throw new Error('device_key.h exists but PICO2KVM_DEV_PUB not found');
    const bytes = [...m[1].matchAll(/0x([0-9a-fA-F]{2})/g)].map((x) =>
      parseInt(x[1], 16),
    );
    if (bytes.length !== 65) throw new Error('PICO2KVM_DEV_PUB is not 65 bytes');
    writeFingerprint(Buffer.from(bytes));
  }
}
